# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cc50de71b98fa378cd2f437c6a9a58481f2466ec6b927a0a5b8e821a17de6a0ef81d01df215032c2cb9e3df22f5d46b061d22aaa00fad60b91c89185172280b

test:
  secret_key_base: 3a460c44acb9edb0d77103ea63c58735725be4ed1d5c451104edf9dd7fe238d8a98eabebd2fc2df73b39bc445a3bc9fefe86391301a7fd18de79ca3167461e88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
